---
- hosts: k8s
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - download_netdata
    - install_netdata
    - setup_child_node
    - setup_stream_conf
    - restart_netdata
    - check_netdata_running
